### ISSUE TITLE
init script: catch traceback when env variable not set (KeyError)

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant-modules#17]
Print some sensible output to STDERR, like _"Environment variable \<var\> needs to be set."_

**Comment by pirat89** [comment]
Current output:
```bash
ModuleSetInitError: Error: Module set init script reported error:
    status: 1
    stderr: Traceback (most recent call last):
    stderr:   File "/usr/share/preupgrade/RHEL6_7/init", line 135, in <module>
    stderr:     scenario = os.environ['PREUPGM_INIT_SCENARIOs'],
    stderr:   File "/usr/lib64/python2.6/UserDict.py", line 22, in __getitem__
    stderr:     raise KeyError(key)
    stderr: KeyError: u'PREUPGM_INIT_SCENARIOs'

```

**Comment by AloisMahdal** [comment]
`u'PREUPGM_INIT_SCENARIOs'`? I do *not* like the `s` at the end... :)

**Comment by AloisMahdal** [comment]
Anyway, is this really necessary?

I mean, user (ie. module developer) does not have any control of the environment; only one place that does is `Application:run_init()`. So if the variable is missing, then only place that needs fixing is that very method.

IOW, this is not user-facing situation; I don't think this can normally happen.

**Comment by AloisMahdal** [comment]
> u'PREUPGM_INIT_SCENARIOs'? I do not like the s at the end... :)

OK, I see now, you just hacked it just to see the traceback... Nice :)

**Comment by bocekm** [comment]
It's nothing critical, just usual "assert" that the required input parameters are available and preventing user from seeing tracebacks. You're right that the user cannot control this, but we shouldn't just expect it won't happen. I guess the error message may be prepended by "Internal error". But it's up to @pirat89, if you close the issue I won't be mad :)

**Comment by AloisMahdal** [comment]
OK., I see, it's true that the message seems to "blame" `init` file, who can't fix the problem.  IOW if anything should be fixed, then it's in run_init.

But that takes us back: many things in `Application` already do depend on these values, so why `run_init()` in particular should be the one that does the checking?  (Actually only role of `run_init()` is that it translates few mandatory properties of `Application()` instance to environment variables.

The way @pirat89 reproduced the traceback above is by injecting typo in `init`. If people make typo, they can immediately see the offending key in the traceback--it's simple thing, wrapping it in other error catching/translation code is IMO not worth it.

**Comment by AloisMahdal** [comment]
Actually I'm not sure what this is exactly about: @bocekm, is this about some environment variables missing (or incorrect) values, then it's matter of something like `Application.__init__` (if that happens, I guess `preupg` would just crash much earlier.

If it's about @pirat89's `init` not being "nice" enough, then again, due to reason above, consumer simply must rely on the API working, there's no reason to complicate its code with another checks.  (Same principle why modules don't check variables/functions provided by common.sh/script_api.sh).
